### ISSUE TITLE
 When will this code be available？

### ISSUE THREAD

**Issue by YePG** [SignLanguageCode/SANet#1]
How can I use your code for research?

**Comment by SignLanguageCode** [comment]
The most important part of SANet has been already made public. As for the whole project, it will not be released due to IP issues. Thank you for your understanding.

**Comment by muxiddin19** [comment]
Great work! However, you still prevent your work from reproducing while everyone, even big IT giants, shares their code openly.
I also want to dive into the SLP field, which is new to me. I liked your work and want to use it in my own one while comparing it with recent SOTA ones. I was suggested to study your work by your coauthors, where that source code is openly published. You may refer to the link: https://github.com/gswycf/SignGraph/issues/6#issuecomment-2184083366
Please share your whole project under a specific license, and at least for research purposes. I hope to receive updates as soon as possible! Good luck in your future works, and hope for a collaborations!
